from __future__ import annotations

from datetime import datetime, timezone
from uuid import UUID

import pytest
from pydantic import ValidationError

from app.schemas.event import EventIn


def _base_payload(**overrides) -> dict:
    base = {
        "ts": "2026-04-28T12:00:00+00:00",
        "source": "cowrie",
        "src_ip": "10.0.0.5",
        "action": "login_failed",
        "raw": {"event": "login_failed"},
    }
    base.update(overrides)
    return base


class TestEventInRequiredFields:
    @pytest.mark.parametrize("missing", ["ts", "source", "src_ip", "action", "raw"])
    def test_missing_required_field_raises(self, missing):
        payload = _base_payload()
        payload.pop(missing)
        with pytest.raises(ValidationError) as exc:
            EventIn(**payload)
        assert missing in str(exc.value)

    def test_minimum_payload_is_accepted(self):
        evt = EventIn(**_base_payload())
        assert evt.source == "cowrie"
        assert evt.action == "login_failed"
        assert evt.src_ip == "10.0.0.5"


class TestEventInDefaults:
    def test_event_id_autogenerated_as_uuid4(self):
        evt = EventIn(**_base_payload())
        assert isinstance(evt.event_id, UUID)
        assert evt.event_id.version == 4

    def test_each_call_generates_unique_event_id(self):
        evt1 = EventIn(**_base_payload())
        evt2 = EventIn(**_base_payload())
        assert evt1.event_id != evt2.event_id

    def test_explicit_event_id_is_preserved(self):
        eid = "11111111-1111-4111-8111-111111111111"
        evt = EventIn(**_base_payload(), event_id=eid)
        assert str(evt.event_id) == eid

    @pytest.mark.parametrize("field", ["object", "trap_id", "user", "host"])
    def test_optional_fields_default_to_none(self, field):
        evt = EventIn(**_base_payload())
        assert getattr(evt, field) is None


class TestEventInTimestamp:
    def test_aware_iso_timestamp_with_tz_accepted(self):
        evt = EventIn(**_base_payload(ts="2026-04-28T12:00:00+03:00"))
        assert evt.ts.tzinfo is not None
        assert evt.ts.utcoffset().total_seconds() == 3 * 3600

    def test_naive_iso_timestamp_accepted(self):
        evt = EventIn(**_base_payload(ts="2026-04-28T12:00:00"))
        assert evt.ts.year == 2026

    def test_datetime_object_accepted(self):
        ts = datetime(2026, 4, 28, 12, 0, tzinfo=timezone.utc)
        evt = EventIn(**_base_payload(ts=ts))
        assert evt.ts == ts

    def test_invalid_timestamp_string_raises(self):
        with pytest.raises(ValidationError):
            EventIn(**_base_payload(ts="not-a-timestamp"))

    def test_unix_epoch_int_is_rejected_or_converted(self):
        evt = EventIn(**_base_payload(ts=1745836800))
        assert evt.ts.year == 2025


class TestEventInRawAny:
    @pytest.mark.parametrize(
        "raw",
        [
            {"event": "login", "user": "root"},
            {"nested": {"a": 1, "b": [1, 2, 3]}},
            ["a", "b", "c"],
            "raw string payload",
            42,
            None,
        ],
    )
    def test_raw_accepts_arbitrary_types(self, raw):
        evt = EventIn(**_base_payload(raw=raw))
        assert evt.raw == raw


class TestEventInStringFields:
    def test_src_ip_is_not_validated_as_ip(self):
        evt = EventIn(**_base_payload(src_ip="not-an-ip"))
        assert evt.src_ip == "not-an-ip"

    def test_long_user_field_not_truncated_at_schema(self):
        long_user = "a" * 5000
        evt = EventIn(**_base_payload(user=long_user))
        assert evt.user == long_user
        assert len(evt.user) == 5000
